
set_property PACKAGE_PIN G19 [get_ports key_in1]
set_property PACKAGE_PIN G20 [get_ports key_in2]
set_property PACKAGE_PIN H15 [get_ports key_in3]

# ±÷”∏¥Œª
set_property PACKAGE_PIN N18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports key_in1]
set_property IOSTANDARD LVCMOS33 [get_ports key_in2]
set_property IOSTANDARD LVCMOS33 [get_ports key_in3]

#TFT_LCD–≈∫≈
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports tft_bl]
set_property IOSTANDARD LVCMOS33 [get_ports tft_clk]
set_property IOSTANDARD LVCMOS33 [get_ports tft_de]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN V12 [get_ports hsync]
set_property PACKAGE_PIN T19 [get_ports tft_bl]
set_property PACKAGE_PIN W15 [get_ports tft_clk]
set_property PACKAGE_PIN V15 [get_ports tft_de]
set_property PACKAGE_PIN W13 [get_ports vsync]
set_property PACKAGE_PIN T15 [get_ports {rgb_tft[15]}]
set_property PACKAGE_PIN T14 [get_ports {rgb_tft[14]}]
set_property PACKAGE_PIN V13 [get_ports {rgb_tft[13]}]
set_property PACKAGE_PIN U13 [get_ports {rgb_tft[12]}]
set_property PACKAGE_PIN U12 [get_ports {rgb_tft[11]}]
set_property PACKAGE_PIN R14 [get_ports {rgb_tft[10]}]
set_property PACKAGE_PIN P14 [get_ports {rgb_tft[9]}]
set_property PACKAGE_PIN P16 [get_ports {rgb_tft[8]}]
set_property PACKAGE_PIN P15 [get_ports {rgb_tft[7]}]
set_property PACKAGE_PIN U17 [get_ports {rgb_tft[6]}]
set_property PACKAGE_PIN T16 [get_ports {rgb_tft[5]}]
set_property PACKAGE_PIN R17 [get_ports {rgb_tft[4]}]
set_property PACKAGE_PIN R16 [get_ports {rgb_tft[3]}]
set_property PACKAGE_PIN U19 [get_ports {rgb_tft[2]}]
set_property PACKAGE_PIN U18 [get_ports {rgb_tft[1]}]
set_property PACKAGE_PIN W19 [get_ports {rgb_tft[0]}]

